"""Add title and description fields to Video table

Revision ID: 00fd35b458f0
Revises: 4b3d70a4e92c
Create Date: 2025-03-21 00:31:59.030352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00fd35b458f0'
down_revision: Union[str, None] = '4b3d70a4e92c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('title', sa.String(), nullable=True))
    op.add_column('videos', sa.Column('description', sa.String(), nullable=True))
    op.add_column('videos', sa.Column('ai_generated_title', sa.String(), nullable=True))
    op.add_column('videos', sa.Column('ai_generated_description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'ai_generated_description')
    op.drop_column('videos', 'ai_generated_title')
    op.drop_column('videos', 'description')
    op.drop_column('videos', 'title')
    # ### end Alembic commands ###
