"""Add explicit content and transcription fields

Revision ID: 3af201c3c131
Revises: 
Create Date: 2025-03-20 23:19:04.743314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3af201c3c131'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('explicit_content', sa.JSON(), nullable=True))
    op.add_column('videos', sa.Column('transcription', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'transcription')
    op.drop_column('videos', 'explicit_content')
    # ### end Alembic commands ###
