"""Add streaming url field

Revision ID: 4b3d70a4e92c
Revises: 3af201c3c131
Create Date: 2025-03-20 23:21:09.662606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b3d70a4e92c'
down_revision: Union[str, None] = '3af201c3c131'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('streaming_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'streaming_url')
    # ### end Alembic commands ###
